### ISSUE TITLE
Custom CSS properties are stripped out when CSS is saved

### ISSUE THREAD

**Issue by krittick** [BrassStack/stylebot#2]
See this issue on the original repo for more details: https://github.com/ankit/stylebot/issues/454

**Example declaration:** 
```css
:root {
    --accent-color: #b5d3f9;
}
```

**Example usage:** 
```css
a { 
    color: var(--accent-color);
}
```

**CSS displayed after saving in Stylebot:**

```css
:root { }
a { }
```

Custom CSS properties documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
